# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cloudsecurity_pb2 as cloudsecurity__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cloudsecurity_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/cloud.UserService/Login',
                request_serializer=cloudsecurity__pb2.LoginRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.LoginResponse.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=cloudsecurity__pb2.LoginRequest.FromString,
                    response_serializer=cloudsecurity__pb2.LoginResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloud.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cloud.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.UserService/Login',
            cloudsecurity__pb2.LoginRequest.SerializeToString,
            cloudsecurity__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EnrollmentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Enroll = channel.unary_unary(
                '/cloud.EnrollmentService/Enroll',
                request_serializer=cloudsecurity__pb2.EnrollRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.EnrollResponse.FromString,
                _registered_method=True)
        self.GetEnrollmentStatus = channel.unary_unary(
                '/cloud.EnrollmentService/GetEnrollmentStatus',
                request_serializer=cloudsecurity__pb2.EnrollmentStatusRequest.SerializeToString,
                response_deserializer=cloudsecurity__pb2.EnrollmentStatusResponse.FromString,
                _registered_method=True)


class EnrollmentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Enroll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEnrollmentStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnrollmentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Enroll': grpc.unary_unary_rpc_method_handler(
                    servicer.Enroll,
                    request_deserializer=cloudsecurity__pb2.EnrollRequest.FromString,
                    response_serializer=cloudsecurity__pb2.EnrollResponse.SerializeToString,
            ),
            'GetEnrollmentStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnrollmentStatus,
                    request_deserializer=cloudsecurity__pb2.EnrollmentStatusRequest.FromString,
                    response_serializer=cloudsecurity__pb2.EnrollmentStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloud.EnrollmentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cloud.EnrollmentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EnrollmentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Enroll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.EnrollmentService/Enroll',
            cloudsecurity__pb2.EnrollRequest.SerializeToString,
            cloudsecurity__pb2.EnrollResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEnrollmentStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.EnrollmentService/GetEnrollmentStatus',
            cloudsecurity__pb2.EnrollmentStatusRequest.SerializeToString,
            cloudsecurity__pb2.EnrollmentStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
