# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloudsecurity.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloudsecurity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63loudsecurity.proto\x12\x05\x63loud\x1a\x1fgoogle/protobuf/timestamp.proto\"/\n\x0cLoginRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"o\n\rLoginResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12.\n\nexpires_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"~\n\rEnrollRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x11\n\tfull_name\x18\x04 \x01(\t\x12\x10\n\x08otp_code\x18\x05 \x01(\t\x12\x18\n\x10storage_limit_mb\x18\x06 \x01(\x03\"f\n\x0e\x45nrollResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x15\n\renrollment_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x1c\n\x14\x61llocated_storage_mb\x18\x04 \x01(\x03\"0\n\x17\x45nrollmentStatusRequest\x12\x15\n\renrollment_id\x18\x01 \x01(\t\"\x9d\x01\n\x18\x45nrollmentStatusResponse\x12\'\n\x06status\x18\x01 \x01(\x0e\x32\x17.cloud.EnrollmentStatus\x12\x0f\n\x07\x64\x65tails\x18\x02 \x01(\t\x12.\n\nupdated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x17\n\x0fotp_destination\x18\x04 \x01(\t*o\n\x10\x45nrollmentStatus\x12!\n\x1d\x45NROLLMENT_STATUS_UNSPECIFIED\x10\x00\x12\x0b\n\x07PENDING\x10\x01\x12\r\n\tCOMPLETED\x10\x02\x12\n\n\x06\x46\x41ILED\x10\x03\x12\x10\n\x0cOTP_REQUIRED\x10\x04\x32\x41\n\x0bUserService\x12\x32\n\x05Login\x12\x13.cloud.LoginRequest\x1a\x14.cloud.LoginResponse2\xa2\x01\n\x11\x45nrollmentService\x12\x35\n\x06\x45nroll\x12\x14.cloud.EnrollRequest\x1a\x15.cloud.EnrollResponse\x12V\n\x13GetEnrollmentStatus\x12\x1e.cloud.EnrollmentStatusRequest\x1a\x1f.cloud.EnrollmentStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloudsecurity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENROLLMENTSTATUS']._serialized_start=667
  _globals['_ENROLLMENTSTATUS']._serialized_end=778
  _globals['_LOGINREQUEST']._serialized_start=63
  _globals['_LOGINREQUEST']._serialized_end=110
  _globals['_LOGINRESPONSE']._serialized_start=112
  _globals['_LOGINRESPONSE']._serialized_end=223
  _globals['_ENROLLREQUEST']._serialized_start=225
  _globals['_ENROLLREQUEST']._serialized_end=351
  _globals['_ENROLLRESPONSE']._serialized_start=353
  _globals['_ENROLLRESPONSE']._serialized_end=455
  _globals['_ENROLLMENTSTATUSREQUEST']._serialized_start=457
  _globals['_ENROLLMENTSTATUSREQUEST']._serialized_end=505
  _globals['_ENROLLMENTSTATUSRESPONSE']._serialized_start=508
  _globals['_ENROLLMENTSTATUSRESPONSE']._serialized_end=665
  _globals['_USERSERVICE']._serialized_start=780
  _globals['_USERSERVICE']._serialized_end=845
  _globals['_ENROLLMENTSERVICE']._serialized_start=848
  _globals['_ENROLLMENTSERVICE']._serialized_end=1010
# @@protoc_insertion_point(module_scope)
