# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: storage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'storage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstorage.proto\x12\x08\x63loudsim\"?\n\x10PutObjectRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"4\n\x11PutObjectResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07size_mb\x18\x02 \x01(\x03\"1\n\x10GetObjectRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\"B\n\x11GetObjectResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x0f\n\x07size_mb\x18\x03 \x01(\x03\"5\n\x12ListObjectsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06prefix\x18\x02 \x01(\t\"+\n\nObjectInfo\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0f\n\x07size_mb\x18\x02 \x01(\x03\"<\n\x13ListObjectsResponse\x12%\n\x07objects\x18\x01 \x03(\x0b\x32\x14.cloudsim.ObjectInfo\"\"\n\x0fGetQuotaRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"5\n\x10GetQuotaResponse\x12\x10\n\x08limit_mb\x18\x01 \x01(\x03\x12\x0f\n\x07used_mb\x18\x02 \x01(\x03\"4\n\x13\x44\x65leteObjectRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\"&\n\x14\x44\x65leteObjectResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2\xfa\x02\n\x0eStorageService\x12\x44\n\tPutObject\x12\x1a.cloudsim.PutObjectRequest\x1a\x1b.cloudsim.PutObjectResponse\x12\x44\n\tGetObject\x12\x1a.cloudsim.GetObjectRequest\x1a\x1b.cloudsim.GetObjectResponse\x12J\n\x0bListObjects\x12\x1c.cloudsim.ListObjectsRequest\x1a\x1d.cloudsim.ListObjectsResponse\x12\x41\n\x08GetQuota\x12\x19.cloudsim.GetQuotaRequest\x1a\x1a.cloudsim.GetQuotaResponse\x12M\n\x0c\x44\x65leteObject\x12\x1d.cloudsim.DeleteObjectRequest\x1a\x1e.cloudsim.DeleteObjectResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'storage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUTOBJECTREQUEST']._serialized_start=27
  _globals['_PUTOBJECTREQUEST']._serialized_end=90
  _globals['_PUTOBJECTRESPONSE']._serialized_start=92
  _globals['_PUTOBJECTRESPONSE']._serialized_end=144
  _globals['_GETOBJECTREQUEST']._serialized_start=146
  _globals['_GETOBJECTREQUEST']._serialized_end=195
  _globals['_GETOBJECTRESPONSE']._serialized_start=197
  _globals['_GETOBJECTRESPONSE']._serialized_end=263
  _globals['_LISTOBJECTSREQUEST']._serialized_start=265
  _globals['_LISTOBJECTSREQUEST']._serialized_end=318
  _globals['_OBJECTINFO']._serialized_start=320
  _globals['_OBJECTINFO']._serialized_end=363
  _globals['_LISTOBJECTSRESPONSE']._serialized_start=365
  _globals['_LISTOBJECTSRESPONSE']._serialized_end=425
  _globals['_GETQUOTAREQUEST']._serialized_start=427
  _globals['_GETQUOTAREQUEST']._serialized_end=461
  _globals['_GETQUOTARESPONSE']._serialized_start=463
  _globals['_GETQUOTARESPONSE']._serialized_end=516
  _globals['_DELETEOBJECTREQUEST']._serialized_start=518
  _globals['_DELETEOBJECTREQUEST']._serialized_end=570
  _globals['_DELETEOBJECTRESPONSE']._serialized_start=572
  _globals['_DELETEOBJECTRESPONSE']._serialized_end=610
  _globals['_STORAGESERVICE']._serialized_start=613
  _globals['_STORAGESERVICE']._serialized_end=991
# @@protoc_insertion_point(module_scope)
